var chart = AmCharts.makeChart("chart_chart02", {
    "type": "xy",
    "theme": "light",
    "autoMarginOffset": 20,
    "path": "http://www.amcharts.com/lib/3/",
    "dataProvider": [{
        "ax": 1,
        "ay": 0.5,
        "bx": 1,
        "by": 2.2
    }, {
        "ax": 2,
        "ay": 1.3,
        "bx": 2,
        "by": 4.9
    }, {
        "ax": 3,
        "ay": 2.3,
        "bx": 3,
        "by": 5.1
    }, {
        "ax": 4,
        "ay": 2.8,
        "bx": 4,
        "by": 5.3
    }, {
        "ax": 5,
        "ay": 3.5,
        "bx": 5,
        "by": 6.1
    }, {
        "ax": 6,
        "ay": 5.1,
        "bx": 6,
        "by": 8.3
    }, {
        "ax": 7,
        "ay": 6.7,
        "bx": 7,
        "by": 10.5
    }, {
        "ax": 8,
        "ay": 8,
        "bx": 8,
        "by": 12.3
    }, {
        "ax": 9,
        "ay": 8.9,
        "bx": 9,
        "by": 14.5
    }, {
        "ax": 10,
        "ay": 9.7,
        "bx": 10,
        "by": 15
    }, {
        "ax": 11,
        "ay": 10.4,
        "bx": 11,
        "by": 18.8
    }, {
        "ax": 12,
        "ay": 11.4,
        "bx": 12,
        "by": 18
    }, {
        "ax": 13,
        "ay": 11.7,
        "bx": 12.5,
        "by": 19
    }],
    "valueAxes": [{
        "position": "bottom",
        "axisAlpha": 100,
		"axisColor": "#d9d9d9",
		"tickLength": "0",
        "dashLength": 0
    }, {
        "axisAlpha": 100,
		"axisColor": "#d9d9d9",
		"tickLength": "0",
        "dashLength": 0,
        "position": "left"
    }],
    "startDuration": 0,
    "graphs": [{
        "balloonText": "Value",
        "bullet": "round",
        "lineAlpha": 0,
        "xField": "ax",
        "yField": "ay",
        "lineColor": "#4462a3",
        "fillAlphas": 0
    }, {
        "balloonText": "Value",
        "bullet": "round",
        "lineAlpha": 0,
        "xField": "bx",
        "yField": "by",
        "lineColor": "#ea8143",
        "fillAlphas": 0
    }],
    "trendLines": [{
        "finalValue": 11,
        "finalXValue": 13,
        "initialValue": 2,
        "initialXValue": 1,
        "lineColor": "#4462a3"
    }, {
        "finalValue": 19,
        "finalXValue": 13,
        "initialValue": 1,
        "initialXValue": 1,
        "lineColor": "#ea8143"
    }],
    "marginLeft": 0,
    "marginBottom": 0,
    "chartScrollbar": false,
	"balloon": {
		"adjustBorderColor": true,
		"fillColor": "#000000",
		"fillAlpha": ".9",
		"shadowAlpha": "0",
		"cornerRadius": "0",
		"borderThickness": "0",
		"color": "#ffffff",
	},
    "export": {
        "enabled": false,
        "position": "bottom-right"
    }
});