var chart = AmCharts.makeChart("chart_activity", {
    "type": "serial",
    "theme": "light",
    "marginTop":10,
    "marginRight": 10,
    "path": "http://www.amcharts.com/lib/3/",
    "dataProvider": [{
        "year": "1990",
        "value": -0.307
    }, {
        "year": "1991",
        "value": -0.168
    }, {
        "year": "1992",
        "value": -0.073
    }, {
        "year": "1993",
        "value": 0
    }, {
        "year": "1994",
        "value": -0.296
    }, {
        "year": "1995",
        "value": -0.217
    }, {
        "year": "1996",
        "value": -0.254
    }, {
        "year": "1997",
        "value": 0.019
    }, {
        "year": "1998",
        "value": -0.063
    }, {
        "year": "1999",
        "value": 0.05
    }, {
        "year": "2000",
        "value": 0.267
    }, {
        "year": "2001",
        "value": 0.311
    }, {
        "year": "2002",
        "value": 0.362
    }, {
        "year": "2003",
        "value": 0.34
    }, {
        "year": "2004",
        "value": 0.36
    }, {
        "year": "2005",
        "value": 0.43
    }, {
        "year": "2006",
        "value": 0.42
    }, {
        "year": "2007",
        "value": 0.41
    }, {
        "year": "2008",
        "value": 0.32
    }, {
        "year": "2009",
        "value": 0.27
    }, {
        "year": "2010",
        "value": 0.23
    }, {
        "year": "2011",
        "value": 0.3
    }, {
        "year": "2012",
        "value": 0.33
    }, {
        "year": "2013",
        "value": 0.4
    }, {
        "year": "2014",
        "value": 0.49
    }, {
        "year": "2015",
        "value": 0.47
    }],
    "valueAxes": [{
        "axisAlpha": 0,
        "position": "left"
    }],
    "graphs": [{
        "id":"g1",
        "balloonText": "Value",
        "bullet": "round",
        "bulletSize": 8,         
        "lineColor": "#3d5aae",
        "lineThickness": 1,
        "negativeLineColor": "#f08000",
        "type": "smoothedLine",
        "valueField": "value"
    }],
    "dataDateFormat": "YYYY",
    "categoryField": "year",
    "categoryAxis": {
        "minPeriod": "YYYY",
		"tickLength": 0,
        "parseDates": true,
		"axisColor": "#d9d9d9",
        "minorGridAlpha": 0.1,
        "minorGridEnabled": true
    },
	"balloon": {
		"adjustBorderColor": true,
		"fillColor": "#000000",
		"fillAlpha": ".9",
		"shadowAlpha": "0",
		"cornerRadius": "0",
		"borderThickness": "0",
		"color": "#ffffff",
	},
    "export": {
        "enabled": true
    }
});